CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);

CREATE TABLE user_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    age INTEGER CHECK (age >= 1),

    CONSTRAINT fk_user_profile_user
        FOREIGN KEY (user_id)
        REFERENCES user_account(id)
        ON DELETE CASCADE
);

CREATE TABLE portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL DEFAULT 'Main Portfolio',

    CONSTRAINT fk_portfolio_user
        FOREIGN KEY (user_id)
        REFERENCES user_account(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_portfolio_user ON portfolio(user_id);

CREATE TABLE portfolio_holding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    asset_id VARCHAR(100) NOT NULL,
    amount NUMERIC(30, 10) NOT NULL,

    CONSTRAINT fk_holding_portfolio
        FOREIGN KEY (portfolio_id)
        REFERENCES portfolio(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_holding_portfolio ON portfolio_holding(portfolio_id);
CREATE INDEX idx_holding_asset ON portfolio_holding(asset_id);

CREATE TABLE crypto_asset (
    id VARCHAR(100) PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(150) NOT NULL
);

CREATE TABLE crypto_price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id VARCHAR(100) NOT NULL,
    price_usd NUMERIC(20, 10) NOT NULL,
    recorded_at DATE NOT NULL,

    CONSTRAINT uq_asset_date UNIQUE (asset_id, recorded_at),

    CONSTRAINT fk_price_asset FOREIGN KEY (asset_id)
        REFERENCES crypto_asset(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_price_asset ON crypto_price_history(asset_id);
CREATE INDEX idx_price_date ON crypto_price_history(recorded_at);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    user_account_id BIGINT NOT NULL REFERENCES user_account(id) ON DELETE CASCADE
);